name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Java Spring application with Gradle
        run: |
           ./gradlew build --no-daemon -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #여기서 자바 스프링 빌드 하고 할 것 넵!!


      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bookflex-backend:latest
          build-args: |
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            AWS_BUCKET_URL=${{ secrets.AWS_BUCKET_URL }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}


      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./bookflex
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bookflex-frontend:latest


      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Change directory
            cd BookFlex
            
            # Stop and remove existing containers
            docker stop bookflex-backend || true
            docker rm bookflex-backend || true
            docker stop bookflex-frontend || true
            docker rm bookflex-frontend || true
            
            # Remove old Docker images
            docker image prune -a -f
            
            # Pull the latest Docker images
            docker pull ${{ secrets.DOCKER_USERNAME }}/bookflex-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/bookflex-frontend:latest

            docker-compose build --no-cache
            
            docker-compose down
       
            # Start the new containers with the latest images
            docker-compose up -d
